# Server configuration
server.port=8080
spring.mvc.view.prefix=/views/
spring.mvc.view.suffix=.jsp

#Database related properties
#database.driver=com.mysql.cj.jdbc.Driver
#database.url=jdbc:mysql://localhost:3306/ecomjava
#database.user=root
#database.password=
#
##Hibernate related properties
#hibernate.dialect=org.hibernate.dialect.MySQL5Dialect
#hibernate.show_sql=true
#hibernate.format_sql=true
#hibernate.hbm2ddl.auto=update


# Hibernate
hibernate.dialect= org.hibernate.dialect.MySQL5Dialect
hibernate.show_sql= true
hibernate.hbm2ddl.auto= update
#entitymanager.packagesToScan:
 
spring.jpa.properties.hibernate.enable_lazy_load_no_trans=true


db.driver= com.mysql.cj.jdbc.Driver
db.url= jdbc:mysql://localhost:3306/ecommjava?createDatabaseIfNotExist=true
db.username= root
db.password=
entitymanager.packagesToScan= com

# PostgreSQL (Supabase) connection
spring.datasource.url=jdbc:postgresql://postgres:Sum@Koo@db.kcnazilnchlfyehgbbun.supabase.co:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=Sum@Koo
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA settings
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
